
import { Vocabulary, TileData } from './types';

export const CATEGORIES = ['General', 'Needs', 'Feelings', 'People', 'Actions', 'Keyboard', 'Saved'] as const;
export const STORAGE_KEY = 'voicebridge_saved_phrases';
export const PINNED_STORAGE_KEY = 'voicebridge_pinned_tiles';

export const VOICE_OPTIONS = [
  { id: 'Puck', label: 'Puck', description: 'Neutral & Clear' },
  { id: 'Charon', label: 'Charon', description: 'Deep & Authoritative' },
  { id: 'Kore', label: 'Kore', description: 'Soft & Soothing' },
  { id: 'Fenrir', label: 'Fenrir', description: 'Energetic & Strong' },
  { id: 'Zephyr', label: 'Zephyr', description: 'Calm & Balanced' },
] as const;

const baseTiles: TileData[] = [
  // --- General Category (Folders Only) ---
  { id: 'folder_connectors', label: 'Words', emoji: '📝', color: 'bg-slate-200 border-slate-400', category: 'General' },
  { id: 'folder_responses', label: 'Responses', emoji: '💬', color: 'bg-blue-100 border-blue-300', category: 'General' },
  { id: 'folder_greetings', label: 'Greetings', emoji: '🤝', color: 'bg-yellow-100 border-yellow-300', category: 'General' },
  { id: 'folder_phrases', label: 'Phrases', emoji: '🗣️', color: 'bg-teal-100 border-teal-300', category: 'General' },
  
  // --- Responses Category ---
  { id: 'back_general', label: 'Go Back', emoji: '🔙', color: 'bg-slate-200 border-slate-300', category: 'Responses', isNavigation: true },
  { id: 'yes', label: 'Yes', emoji: '✅', color: 'bg-green-100 border-green-300', category: 'Responses' },
  { id: 'no', label: 'No', emoji: '❌', color: 'bg-red-100 border-red-300', category: 'Responses' },
  { id: 'please', label: 'Please', emoji: '🙏', color: 'bg-yellow-100 border-yellow-300', category: 'Responses' },
  { id: 'thanks', label: 'Thanks', emoji: '🙌', color: 'bg-blue-100 border-blue-300', category: 'Responses' },
  { id: 'maybe', label: 'Maybe', emoji: '🤷', color: 'bg-orange-100 border-orange-300', category: 'Responses' },
  { id: 'ok', label: 'OK', emoji: '👌', color: 'bg-green-100 border-green-300', category: 'Responses' },
  { id: 'idk', label: 'I don\'t know', emoji: '🤔', color: 'bg-slate-100 border-slate-300', category: 'Responses' },

  // --- Greetings Category ---
  { id: 'back_general', label: 'Go Back', emoji: '🔙', color: 'bg-slate-200 border-slate-300', category: 'Greetings', isNavigation: true },
  { id: 'hello', label: 'Hello', emoji: '👋', color: 'bg-purple-100 border-purple-300', category: 'Greetings' },
  { id: 'goodbye', label: 'Bye', emoji: '👋', color: 'bg-slate-100 border-slate-300', category: 'Greetings' },
  { id: 'good_morning', label: 'Good Morning', emoji: '🌅', color: 'bg-yellow-100 border-yellow-300', category: 'Greetings' },
  { id: 'good_night', label: 'Good Night', emoji: '🌙', color: 'bg-indigo-100 border-indigo-300', category: 'Greetings' },
  { id: 'how_are_you', label: 'How are you?', emoji: '❓', color: 'bg-blue-100 border-blue-300', category: 'Greetings' },
  { id: 'nice_meet', label: 'Nice to meet you', emoji: '🤝', color: 'bg-green-100 border-green-300', category: 'Greetings' },

  // --- Connectors (Words) Category ---
  { id: 'back_general', label: 'Go Back', emoji: '🔙', color: 'bg-slate-200 border-slate-300', category: 'Connectors', isNavigation: true },
  
  // High Frequency Verbs & Modifiers
  { id: 'want_c', label: 'Want', emoji: '🤲', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },
  { id: 'need_c', label: 'Need', emoji: '🆘', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },
  { id: 'more_c', label: 'More', emoji: '➕', color: 'bg-green-50 border-green-200', category: 'Connectors' },
  { id: 'not_c', label: 'Not', emoji: '🚫', color: 'bg-red-50 border-red-200', category: 'Connectors' },
  { id: 'like_c', label: 'Like', emoji: '👍', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },
  { id: 'can_c', label: 'Can', emoji: '💪', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },
  { id: 'do_c', label: 'Do', emoji: '🔨', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },
  { id: 'will_c', label: 'Will', emoji: '🔜', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },

  // Pronouns
  { id: 'i', label: 'I', emoji: '🙋', color: 'bg-white border-slate-300', category: 'Connectors' },
  { id: 'you', label: 'You', emoji: '👉', color: 'bg-white border-slate-300', category: 'Connectors' },
  { id: 'we', label: 'We', emoji: '👥', color: 'bg-white border-slate-300', category: 'Connectors' },
  { id: 'they', label: 'They', emoji: '👉👉', color: 'bg-white border-slate-300', category: 'Connectors' },
  { id: 'it', label: 'It', emoji: '📦', color: 'bg-white border-slate-300', category: 'Connectors' },
  { id: 'my', label: 'My', emoji: '🤲', color: 'bg-white border-slate-300', category: 'Connectors' },
  { id: 'your', label: 'Your', emoji: '🫵', color: 'bg-white border-slate-300', category: 'Connectors' },
  { id: 'he', label: 'He', emoji: '👨', color: 'bg-white border-slate-300', category: 'Connectors' },
  { id: 'she', label: 'She', emoji: '👩', color: 'bg-white border-slate-300', category: 'Connectors' },
  
  // Verbs (To Be)
  { id: 'am', label: 'Am', emoji: '🟢', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },
  { id: 'is', label: 'Is', emoji: '👉', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },
  { id: 'are', label: 'Are', emoji: '👥', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },
  { id: 'was', label: 'Was', emoji: '🔙', color: 'bg-amber-50 border-amber-200', category: 'Connectors' },
  
  // Prepositions / Articles
  { id: 'to', label: 'To', emoji: '➡️', color: 'bg-blue-50 border-blue-200', category: 'Connectors' },
  { id: 'for', label: 'For', emoji: '🎁', color: 'bg-blue-50 border-blue-200', category: 'Connectors' },
  { id: 'with', label: 'With', emoji: '🤝', color: 'bg-blue-50 border-blue-200', category: 'Connectors' },
  { id: 'in', label: 'In', emoji: '⬇️', color: 'bg-blue-50 border-blue-200', category: 'Connectors' },
  { id: 'on', label: 'On', emoji: '⬆️', color: 'bg-blue-50 border-blue-200', category: 'Connectors' },
  { id: 'at', label: 'At', emoji: '📍', color: 'bg-blue-50 border-blue-200', category: 'Connectors' },
  { id: 'and', label: 'And', emoji: '➕', color: 'bg-purple-50 border-purple-200', category: 'Connectors' },
  { id: 'but', label: 'But', emoji: '✋', color: 'bg-purple-50 border-purple-200', category: 'Connectors' },
  { id: 'the', label: 'The', emoji: '#️⃣', color: 'bg-purple-50 border-purple-200', category: 'Connectors' },
  { id: 'this', label: 'This', emoji: '👇', color: 'bg-purple-50 border-purple-200', category: 'Connectors' },
  { id: 'that', label: 'That', emoji: '👆', color: 'bg-purple-50 border-purple-200', category: 'Connectors' },
  { id: 'because', label: 'Because', emoji: '💡', color: 'bg-purple-50 border-purple-200', category: 'Connectors' },

  // --- Needs (Target: 30+) ---
  { id: 'water', label: 'Water', emoji: '💧', color: 'bg-blue-200 border-blue-400', category: 'Needs' },
  { id: 'food', label: 'Food', emoji: '🍎', color: 'bg-orange-200 border-orange-400', category: 'Needs' },
  { id: 'toilet', label: 'Toilet', emoji: '🚽', color: 'bg-cyan-200 border-cyan-400', category: 'Needs' },
  { id: 'help', label: 'Help', emoji: '🆘', color: 'bg-red-200 border-red-400', category: 'Needs' },
  { id: 'pain', label: 'Pain', emoji: '🤕', color: 'bg-red-200 border-red-400', category: 'Needs' },
  { id: 'hot', label: 'Hot', emoji: '🥵', color: 'bg-orange-100 border-orange-300', category: 'Needs' },
  { id: 'cold', label: 'Cold', emoji: '🥶', color: 'bg-cyan-100 border-cyan-300', category: 'Needs' },
  { id: 'medicine', label: 'Medicine', emoji: '💊', color: 'bg-pink-100 border-pink-300', category: 'Needs' },
  { id: 'glasses', label: 'Glasses', emoji: '👓', color: 'bg-slate-100 border-slate-300', category: 'Needs' },
  { id: 'break', label: 'Break', emoji: '⏸️', color: 'bg-green-100 border-green-300', category: 'Needs' },
  { id: 'rest', label: 'Rest', emoji: '🛋️', color: 'bg-indigo-100 border-indigo-300', category: 'Needs' },
  { id: 'quiet', label: 'Quiet', emoji: '🤫', color: 'bg-indigo-100 border-indigo-300', category: 'Needs' },
  { id: 'light_on', label: 'Light On', emoji: '💡', color: 'bg-yellow-100 border-yellow-300', category: 'Needs' },
  { id: 'light_off', label: 'Light Off', emoji: '🌑', color: 'bg-slate-300 border-slate-500', category: 'Needs' },
  { id: 'charger', label: 'Charger', emoji: '🔌', color: 'bg-slate-100 border-slate-300', category: 'Needs' },
  { id: 'phone', label: 'Phone', emoji: '📱', color: 'bg-blue-100 border-blue-300', category: 'Needs' },
  { id: 'blanket', label: 'Blanket', emoji: '🛌', color: 'bg-blue-100 border-blue-300', category: 'Needs' },
  { id: 'pillow', label: 'Pillow', emoji: '🛏️', color: 'bg-white border-slate-300', category: 'Needs' },
  { id: 'tissue', label: 'Tissue', emoji: '🤧', color: 'bg-white border-slate-300', category: 'Needs' },
  { id: 'shower', label: 'Shower', emoji: '🚿', color: 'bg-cyan-100 border-cyan-300', category: 'Needs' },
  { id: 'wash_hands', label: 'Wash Hands', emoji: '🧼', color: 'bg-cyan-100 border-cyan-300', category: 'Needs' },
  { id: 'brush_teeth', label: 'Brush Teeth', emoji: '🪥', color: 'bg-cyan-100 border-cyan-300', category: 'Needs' },
  { id: 'clothes', label: 'Clothes', emoji: '👕', color: 'bg-purple-100 border-purple-300', category: 'Needs' },
  { id: 'shoes', label: 'Shoes', emoji: '👟', color: 'bg-slate-100 border-slate-300', category: 'Needs' },
  { id: 'coat', label: 'Coat', emoji: '🧥', color: 'bg-blue-100 border-blue-300', category: 'Needs' },
  { id: 'bag', label: 'Bag', emoji: '🎒', color: 'bg-orange-100 border-orange-300', category: 'Needs' },
  { id: 'money', label: 'Money', emoji: '💵', color: 'bg-green-100 border-green-300', category: 'Needs' },
  { id: 'key', label: 'Key', emoji: '🔑', color: 'bg-yellow-100 border-yellow-300', category: 'Needs' },
  { id: 'wheelchair', label: 'Wheelchair', emoji: '🦽', color: 'bg-slate-100 border-slate-300', category: 'Needs' },
  { id: 'suction', label: 'Suction', emoji: '💨', color: 'bg-slate-100 border-slate-300', category: 'Needs' },
  { id: 'reposition', label: 'Move Me', emoji: '🔄', color: 'bg-orange-100 border-orange-300', category: 'Needs' },
  { id: 'itch', label: 'Itch', emoji: '🤏', color: 'bg-red-100 border-red-300', category: 'Needs' },
  { id: 'nausea', label: 'Nausea', emoji: '🤢', color: 'bg-green-100 border-green-300', category: 'Needs' },

  // --- Feelings (Target: 30+) ---
  { id: 'happy', label: 'Happy', emoji: '😊', color: 'bg-yellow-200 border-yellow-400', category: 'Feelings' },
  { id: 'sad', label: 'Sad', emoji: '😢', color: 'bg-blue-200 border-blue-400', category: 'Feelings' },
  { id: 'tired', label: 'Tired', emoji: '😴', color: 'bg-indigo-200 border-indigo-400', category: 'Feelings' },
  { id: 'angry', label: 'Angry', emoji: '😠', color: 'bg-red-200 border-red-400', category: 'Feelings' },
  { id: 'scared', label: 'Scared', emoji: '😨', color: 'bg-purple-200 border-purple-400', category: 'Feelings' },
  { id: 'love', label: 'Love', emoji: '❤️', color: 'bg-pink-200 border-pink-400', category: 'Feelings' },
  { id: 'excited', label: 'Excited', emoji: '🤩', color: 'bg-yellow-200 border-yellow-400', category: 'Feelings' },
  { id: 'bored', label: 'Bored', emoji: '😐', color: 'bg-slate-200 border-slate-400', category: 'Feelings' },
  { id: 'confused', label: 'Confused', emoji: '😕', color: 'bg-orange-200 border-orange-400', category: 'Feelings' },
  { id: 'frustrated', label: 'Frustrated', emoji: '😤', color: 'bg-red-200 border-red-400', category: 'Feelings' },
  { id: 'sick', label: 'Sick', emoji: '🤢', color: 'bg-green-200 border-green-400', category: 'Feelings' },
  { id: 'silly', label: 'Silly', emoji: '🤪', color: 'bg-pink-200 border-pink-400', category: 'Feelings' },
  { id: 'surprised', label: 'Surprised', emoji: '😮', color: 'bg-yellow-200 border-yellow-400', category: 'Feelings' },
  { id: 'shy', label: 'Shy', emoji: '🫣', color: 'bg-purple-200 border-purple-400', category: 'Feelings' },
  { id: 'proud', label: 'Proud', emoji: '😌', color: 'bg-yellow-200 border-yellow-400', category: 'Feelings' },
  { id: 'nervous', label: 'Nervous', emoji: '😬', color: 'bg-orange-200 border-orange-400', category: 'Feelings' },
  { id: 'lonely', label: 'Lonely', emoji: '😞', color: 'bg-blue-200 border-blue-400', category: 'Feelings' },
  { id: 'calm', label: 'Calm', emoji: '🧘', color: 'bg-green-200 border-green-400', category: 'Feelings' },
  { id: 'grateful', label: 'Grateful', emoji: '🙏', color: 'bg-yellow-200 border-yellow-400', category: 'Feelings' },
  { id: 'hopeful', label: 'Hopeful', emoji: '🤞', color: 'bg-blue-200 border-blue-400', category: 'Feelings' },
  { id: 'safe', label: 'Safe', emoji: '🛡️', color: 'bg-green-200 border-green-400', category: 'Feelings' },
  { id: 'unsafe', label: 'Unsafe', emoji: '⚠️', color: 'bg-red-200 border-red-400', category: 'Feelings' },
  { id: 'annoyed', label: 'Annoyed', emoji: '😒', color: 'bg-orange-200 border-orange-400', category: 'Feelings' },
  { id: 'jealous', label: 'Jealous', emoji: '😒', color: 'bg-green-200 border-green-400', category: 'Feelings' },
  { id: 'overwhelmed', label: 'Too Much', emoji: '🤯', color: 'bg-red-200 border-red-400', category: 'Feelings' },
  { id: 'hurt', label: 'Hurt', emoji: '🤕', color: 'bg-red-200 border-red-400', category: 'Feelings' },
  { id: 'thirsty', label: 'Thirsty', emoji: '🥤', color: 'bg-blue-200 border-blue-400', category: 'Feelings' },
  { id: 'hungry', label: 'Hungry', emoji: '🍔', color: 'bg-orange-200 border-orange-400', category: 'Feelings' },
  { id: 'worried', label: 'Worried', emoji: '😟', color: 'bg-slate-200 border-slate-400', category: 'Feelings' },
  { id: 'disappointed', label: 'Disappointed', emoji: '😞', color: 'bg-blue-200 border-blue-400', category: 'Feelings' },
  { id: 'comfortable', label: 'Comfortable', emoji: '😌', color: 'bg-green-200 border-green-400', category: 'Feelings' },
  { id: 'uncomfortable', label: 'Uncomfortable', emoji: '😣', color: 'bg-orange-200 border-orange-400', category: 'Feelings' },

  // --- Actions (Target: 30+) ---
  { id: 'want', label: 'Want', emoji: '🤲', color: 'bg-emerald-200 border-emerald-400', category: 'Actions' },
  { id: 'go', label: 'Go', emoji: '🚶', color: 'bg-green-200 border-green-400', category: 'Actions' },
  { id: 'stop', label: 'Stop', emoji: '🛑', color: 'bg-red-200 border-red-400', category: 'Actions' },
  { id: 'look', label: 'Look', emoji: '👀', color: 'bg-blue-200 border-blue-400', category: 'Actions' },
  { id: 'listen', label: 'Listen', emoji: '👂', color: 'bg-yellow-200 border-yellow-400', category: 'Actions' },
  { id: 'sleep', label: 'Sleep', emoji: '🛌', color: 'bg-indigo-200 border-indigo-400', category: 'Actions' },
  { id: 'eat', label: 'Eat', emoji: '🍽️', color: 'bg-orange-200 border-orange-400', category: 'Actions' },
  { id: 'drink', label: 'Drink', emoji: '🥤', color: 'bg-blue-200 border-blue-400', category: 'Actions' },
  { id: 'play', label: 'Play', emoji: '🎮', color: 'bg-purple-200 border-purple-400', category: 'Actions' },
  { id: 'read', label: 'Read', emoji: '📖', color: 'bg-yellow-200 border-yellow-400', category: 'Actions' },
  { id: 'write', label: 'Write', emoji: '✍️', color: 'bg-slate-200 border-slate-400', category: 'Actions' },
  { id: 'draw', label: 'Draw', emoji: '🎨', color: 'bg-pink-200 border-pink-400', category: 'Actions' },
  { id: 'watch', label: 'Watch TV', emoji: '📺', color: 'bg-slate-200 border-slate-400', category: 'Actions' },
  { id: 'walk', label: 'Walk', emoji: '🚶', color: 'bg-green-200 border-green-400', category: 'Actions' },
  { id: 'run', label: 'Run', emoji: '🏃', color: 'bg-orange-200 border-orange-400', category: 'Actions' },
  { id: 'sit', label: 'Sit', emoji: '🪑', color: 'bg-slate-200 border-slate-400', category: 'Actions' },
  { id: 'stand', label: 'Stand', emoji: '🧍', color: 'bg-slate-200 border-slate-400', category: 'Actions' },
  { id: 'talk', label: 'Talk', emoji: '🗣️', color: 'bg-blue-200 border-blue-400', category: 'Actions' },
  { id: 'think', label: 'Think', emoji: '💭', color: 'bg-slate-200 border-slate-400', category: 'Actions' },
  { id: 'wait', label: 'Wait', emoji: '⏳', color: 'bg-yellow-200 border-yellow-400', category: 'Actions' },
  { id: 'give', label: 'Give', emoji: '🎁', color: 'bg-pink-200 border-pink-400', category: 'Actions' },
  { id: 'take', label: 'Take', emoji: '🤏', color: 'bg-blue-200 border-blue-400', category: 'Actions' },
  { id: 'open', label: 'Open', emoji: '🔓', color: 'bg-green-200 border-green-400', category: 'Actions' },
  { id: 'close', label: 'Close', emoji: '🔒', color: 'bg-red-200 border-red-400', category: 'Actions' },
  { id: 'wash', label: 'Wash', emoji: '🧼', color: 'bg-cyan-200 border-cyan-400', category: 'Actions' },
  { id: 'clean', label: 'Clean', emoji: '🧹', color: 'bg-slate-200 border-slate-400', category: 'Actions' },
  { id: 'cook', label: 'Cook', emoji: '🍳', color: 'bg-orange-200 border-orange-400', category: 'Actions' },
  { id: 'buy', label: 'Buy', emoji: '🛒', color: 'bg-green-200 border-green-400', category: 'Actions' },
  { id: 'find', label: 'Find', emoji: '🔍', color: 'bg-yellow-200 border-yellow-400', category: 'Actions' },
  { id: 'call', label: 'Call', emoji: '📞', color: 'bg-blue-200 border-blue-400', category: 'Actions' },
  { id: 'text', label: 'Text', emoji: '💬', color: 'bg-blue-200 border-blue-400', category: 'Actions' },
  { id: 'laugh', label: 'Laugh', emoji: '😂', color: 'bg-yellow-200 border-yellow-400', category: 'Actions' },
  { id: 'cry', label: 'Cry', emoji: '😭', color: 'bg-blue-200 border-blue-400', category: 'Actions' },
  { id: 'hug', label: 'Hug', emoji: '🫂', color: 'bg-pink-200 border-pink-400', category: 'Actions' },
  { id: 'kiss', label: 'Kiss', emoji: '💋', color: 'bg-red-200 border-red-400', category: 'Actions' },

  // --- People (Target: 30+) ---
  { id: 'me', label: 'Me', emoji: '🙋', color: 'bg-teal-200 border-teal-400', category: 'People' },
  { id: 'you', label: 'You', emoji: '👉', color: 'bg-teal-200 border-teal-400', category: 'People' },
  { id: 'mom', label: 'Mom', emoji: '👩', color: 'bg-pink-100 border-pink-300', category: 'People' },
  { id: 'dad', label: 'Dad', emoji: '👨', color: 'bg-blue-100 border-blue-300', category: 'People' },
  { id: 'sister', label: 'Sister', emoji: '👧', color: 'bg-pink-100 border-pink-300', category: 'People' },
  { id: 'brother', label: 'Brother', emoji: '👦', color: 'bg-blue-100 border-blue-300', category: 'People' },
  { id: 'grandma', label: 'Grandma', emoji: '👵', color: 'bg-pink-100 border-pink-300', category: 'People' },
  { id: 'grandpa', label: 'Grandpa', emoji: '👴', color: 'bg-blue-100 border-blue-300', category: 'People' },
  { id: 'family', label: 'Family', emoji: '👨‍👩‍👧', color: 'bg-white border-slate-200', category: 'People' },
  { id: 'friend', label: 'Friend', emoji: '🤝', color: 'bg-green-100 border-green-300', category: 'People' },
  { id: 'teacher', label: 'Teacher', emoji: '🧑‍🏫', color: 'bg-yellow-100 border-yellow-300', category: 'People' },
  { id: 'doctor', label: 'Doctor', emoji: '👨‍⚕️', color: 'bg-white border-slate-200', category: 'People' },
  { id: 'nurse', label: 'Nurse', emoji: '👩‍⚕️', color: 'bg-white border-slate-200', category: 'People' },
  { id: 'therapist', label: 'Therapist', emoji: '📋', color: 'bg-white border-slate-200', category: 'People' },
  { id: 'caregiver', label: 'Caregiver', emoji: '🤗', color: 'bg-white border-slate-200', category: 'People' },
  { id: 'police', label: 'Police', emoji: '👮', color: 'bg-blue-100 border-blue-300', category: 'People' },
  { id: 'firefighter', label: 'Firefighter', emoji: '🧑‍🚒', color: 'bg-red-100 border-red-300', category: 'People' },
  { id: 'baby', label: 'Baby', emoji: '👶', color: 'bg-yellow-100 border-yellow-300', category: 'People' },
  { id: 'boy', label: 'Boy', emoji: '👦', color: 'bg-blue-100 border-blue-300', category: 'People' },
  { id: 'girl', label: 'Girl', emoji: '👧', color: 'bg-pink-100 border-pink-300', category: 'People' },
  { id: 'man', label: 'Man', emoji: '👨', color: 'bg-slate-100 border-slate-300', category: 'People' },
  { id: 'woman', label: 'Woman', emoji: '👩', color: 'bg-slate-100 border-slate-300', category: 'People' },
  { id: 'stranger', label: 'Stranger', emoji: '👤', color: 'bg-slate-300 border-slate-400', category: 'People' },
  { id: 'pet', label: 'Pet', emoji: '🐾', color: 'bg-orange-100 border-orange-300', category: 'People' },
  { id: 'dog', label: 'Dog', emoji: '🐕', color: 'bg-orange-100 border-orange-300', category: 'People' },
  { id: 'cat', label: 'Cat', emoji: '🐈', color: 'bg-orange-100 border-orange-300', category: 'People' },
  { id: 'everyone', label: 'Everyone', emoji: '👥', color: 'bg-slate-100 border-slate-300', category: 'People' },
  { id: 'nobody', label: 'Nobody', emoji: '🚫', color: 'bg-slate-100 border-slate-300', category: 'People' },
  { id: 'driver', label: 'Driver', emoji: '🚍', color: 'bg-yellow-100 border-yellow-300', category: 'People' },
  { id: 'aide', label: 'Aide', emoji: '🆘', color: 'bg-red-100 border-red-300', category: 'People' },
  { id: 'cousin', label: 'Cousin', emoji: '🧑‍🤝‍🧑', color: 'bg-purple-100 border-purple-300', category: 'People' },
  { id: 'uncle', label: 'Uncle', emoji: '🧔', color: 'bg-blue-100 border-blue-300', category: 'People' },
  { id: 'aunt', label: 'Aunt', emoji: '👩‍🦱', color: 'bg-pink-100 border-pink-300', category: 'People' },

  // --- Phrases (Target: 30) ---
  { id: 'back_general', label: 'Go Back', emoji: '🔙', color: 'bg-slate-200 border-slate-300', category: 'Phrases', isNavigation: true },
  { id: 'phr_1', label: 'I use this device to talk.', emoji: '🗣️', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_2', label: 'Please be patient.', emoji: '⏳', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_3', label: 'I understand.', emoji: '👍', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_4', label: 'I do not understand.', emoji: '🤷', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_5', label: 'Please say it again.', emoji: '🔁', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_6', label: 'Can you write it down?', emoji: '✍️', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_7', label: 'I need a doctor.', emoji: '👨‍⚕️', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_8', label: 'Call 911.', emoji: '🚨', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_9', label: 'Where is the bathroom?', emoji: '🚻', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_10', label: 'I am comfortable.', emoji: '😌', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_11', label: 'I am uncomfortable.', emoji: '😣', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_12', label: 'Change the channel.', emoji: '📺', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_13', label: 'What are we doing?', emoji: '❓', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_14', label: 'I want to go outside.', emoji: '🌳', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_15', label: 'I want to stay inside.', emoji: '🏠', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_16', label: 'Please charge my device.', emoji: '🔋', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_17', label: 'How much does this cost?', emoji: '💲', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_18', label: 'It is too loud.', emoji: '🔊', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_19', label: 'It is too quiet.', emoji: '🔈', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_20', label: 'I am bored.', emoji: '😐', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_21', label: 'Can I have some water?', emoji: '💧', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_22', label: 'I am finished.', emoji: '🏁', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_23', label: 'Not yet.', emoji: '⏳', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_24', label: 'Good job.', emoji: '👏', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_25', label: 'Happy Birthday.', emoji: '🎂', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_26', label: 'Happy Holidays.', emoji: '🎄', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_27', label: 'Congratulations.', emoji: '🎉', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_28', label: 'I missed you.', emoji: '🫂', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_29', label: 'See you later.', emoji: '👋', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
  { id: 'phr_30', label: 'I love you.', emoji: '❤️', color: 'bg-teal-50 border-teal-200', category: 'Phrases' },
];

export const VOCABULARY: Vocabulary = baseTiles.reduce((acc, tile) => {
  if (!acc[tile.category]) {
    acc[tile.category] = [];
  }
  acc[tile.category].push(tile);
  return acc;
}, {} as Vocabulary);
